services:
  db:
    image: postgres:15
    container_name: library_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    env_file:
      - .env
    build: .
    container_name: library_web
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SECRET_KEY=django-insecure-change-me-in-production
      - DEBUG=1
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
